name: analise_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - xlrd
  - openpyxl
  - mlxtend
  - seaborn
  - plotly

